language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-react-spa' ]; then cd .. && eval "mv $currentfolder generator-react-spa" && cd generator-react-spa; fi

